### ISSUE TITLE
[BUG] Refund last purchased or all purchased

### ISSUE THREAD

**Issue by halfwayz1** [BennyExtreme/KBotExt#12]
### Version

1.4.6

### Where

Champs

### Server

BR (Brazil)

### Details

when I try to refund any champion I either get a 'too many requests' or 'refund ineligible' error

with the refund all champions option, it appears that I have been refunded, but the champion continues or consumes one of my available refunds, I am using the x64 version, as administrator, I have tried x86 and the same thing happens

has this glitch been patched or am I doing something wrong?

### Steps to reproduce

buy any champ and try to use one of refund glitchs

**Comment by BennyExtreme** [comment]
> When I try to refund any champion I either get a 'too many requests' or 'refund ineligible' error

They seem to have added extra controls and restrictions...
So yes, sadly it's kinda patched.
