### ISSUE TITLE
[FEATURE] Auto Multi-Search

### ISSUE THREAD

**Issue by squidmafia** [BennyExtreme/KBotExt#14]
### Where

Game

### Details

Multi-Search functioning automatically to whichever site it's set to when reaching champ-select without having to click the button every time. Button to toggle to the left of the multi-search button would be great.

**Comment by BennyExtreme** [comment]
Added in [v1.5.0](https://github.com/BennyExtreme/KBotExt/releases/tag/1.5.0) ([Update](https://github.com/BennyExtreme/KBotExt/commit/d2de6565624d3434dd83796a593f9b8a0881ac5b))
