### ISSUE TITLE
[FEATURE] invite spammer

### ISSUE THREAD

**Issue by chinesedoinb** [BennyExtreme/KBotExt#3]
### Details

so they can spam & crash
pleb
invite spammer works like:
1. joing q
2. invite  target
3. change/leave q
4. invite again

**Comment by BennyExtreme** [comment]
> use TUTORIAL ARAM CUSTOM

More info on that edit, thanks!

Loop:
- Create a lobby (Maybe in Clash [?])
- Send the invitation to the player
- Delete the lobby

It seems to work, is the concept right?

**Comment by chinesedoinb** [comment]
> > use TUTORIAL ARAM CUSTOM
> 
> More info on that edit, thanks!
> 
> Loop:
> 
> * Create a lobby (Maybe in Clash [?])
> * Send the invitation to the player
> * Delete the lobby
> 
> It seems to work, is the concept right?

clash lobby have rate limit

**Comment by chinesedoinb** [comment]
![image](https://user-images.githubusercontent.com/93780588/200529159-99207c0e-a85f-4421-8111-0cb7dfbff6c6.png)
use this lobby

**Comment by BennyExtreme** [comment]
Watch the latest version released.

I did it with the Clash game mode as I mentioned initially, it does not have an extremely fast speed (even attacking with several PCs simultaneously), so it seems limited by the victim client.
You can send as many invitations as you want, but I recommend using a second account (maybe created specifically for that), the account will be rate limited but the invites will continue to work and will still be sent.
Waiting a little while you also regain the other normal features of the client (like changing your status, adding friends and more).

Notes:
- if you want to stop an ongoing attack set the number of invitations to 0 during the attack.
- if you want to bypass the maximum of 100 invitations that I set on the slider you can hold the ctrl key on the keyboard and left click on the slider, it will allow you to enter a numeric value at your convenience. (PS: this operation is valid with all sliders)
