### ISSUE TITLE
When swapping pick order with another player auto Lock In and auto Ban break

### ISSUE THREAD

**Issue by iloveleagueoflegends123** [BennyExtreme/KBotExt#5]
### Version

1.17

### Where

None

### Details

When you swap pick order it tries to lock in but cant for some reason same with banning if swap early enough (before ban phase)

### Steps to reproduce

Swap with another player

**Comment by BennyExtreme** [comment]
Should have been resolved by commit [880070c](https://github.com/BennyExtreme/KBotExt/commit/880070c1432dff6e82b649be0e699795f422f480)
